management:
#  server:
#    port: 8541
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
server:
  port: 9801

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
      bindings:
        input:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.zq: DEBUG


