server:
  port: 8888
spring:
  config:
    name: config
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: file://${user.dir}/spring-cloud-config-server-git/src/main/resources/config