server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: discovery

---

server:
  port: 8762
spring:
  profiles: peer1
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8763/eureka/
  instance:
    hostname: peer1

---

server:
  port: 8763
spring:
  profiles: peer2
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8762/eureka/
  instance:
      hostname: peer2