
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
server:
  port: 9800
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
      bindings:
        output:
          destination: orgChangeTopic
          content-type: application/json
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.zq: DEBUG
